Ensure email prefix valid for TRN Sign-In journey
DFE-Digital/get-an-identity pull request #411
Opened 2023-02-08 17:25 UTC by wilpow-github

### Context

As an Identity administrator
I want to prevent users signing up with shared email addresses
So that users do not lose access to their account when they change jobs

### Changes proposed in this pull request

Validate supplied Email does not have invalid prefix in list

### Checklist

-   [ ] Attach to Trello card
-   [ ] Rebased master
-   [ ] Cleaned commit history
-   [ ] Tested by running locally
-   [ ] Reminder created to manually clean any removed app settings post deployment

2023-02-08 18:45 UTC, gunndabad approved these changes

2023-02-08 18:46 UTC, gunndabad requested changes
Need to check if we already have a user with the email address before we fail; we don't want to stop any existing users from signing in, even if their email is shared (we can fix that later).

2023-02-09 09:57 UTC, wilpow-github commented on dotnet-authserver/src/TeacherIdentity.AuthServer/Pages/SignIn/Email.cshtml.cs
> +            var existingUser = await _dbContext.Users.Where(user => user.EmailAddress == Email).SingleOrDefaultAsync();
Not checking for Default User type as I believe this applies to all Users

2023-02-09 09:58 UTC, gunndabad approved these changes

2023-02-09 10:48 UTC, merged